name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Ensure package cache folder exists
        run: mkdir -p ~/.xmake/packages

      - name: Ensure build cache folder exists
        run: mkdir -p build/.xmake

      - name: Cache xmake packages
        uses: actions/cache@v4
        with:
          path: ~/.xmake/packages
          key: ${{ runner.os }}-xmake-packages-${{ hashFiles('xmake.lua') }}

      - name: Cache xmake build
        uses: actions/cache@v4
        with:
          path: build/.xmake
          key: ${{ runner.os }}-xmake-build-${{ hashFiles('xmake.lua') }}

      - name: Setup
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          package-cache-key: 'stfc-mod-ci-win'

      - name: Configure
        run: xmake f -m release -y

      - name: Build
        run: xmake -y

      - name: Package
        run: mv build/windows/x64/release/stfc-community-patch.dll version.dll

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stfc-community-patch
          path: version.dll

  build-mac:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Ensure package cache folder exists
        run: mkdir -p ~/.xmake/packages

      - name: Ensure build cache folder exists
        run: mkdir -p build/.xmake

      - name: Cache xmake packages
        uses: actions/cache@v4
        with:
          path: ~/.xmake/packages
          key: ${{ runner.os }}-xmake-packages-${{ hashFiles('xmake.lua') }}

      - name: Cache xmake build
        uses: actions/cache@v4
        with:
          path: build/.xmake
          key: ${{ runner.os }}-xmake-build-${{ hashFiles('xmake.lua') }}

      - name: Set up xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          package-cache-key: 'stfc-mod-ci-mac'

      - name: Configure (arm64)
        run: xmake f -p macosx -a "arm64" -m release -y

      - name: Build (arm64)
        run: xmake -y

      - name: Configure (x86)
        run: xmake f -p macosx -a "x86_64" -m release -y

      - name: Build (x84)
        run: xmake -y

      - name: Create Universal App Bundle
        run: |
          lipo -create build/macosx/arm64/release/macOSLauncher build/macosx/x86_64/release/macOSLauncher -output build/macosx/arm64/release/macOSLauncher.app/Contents/MacOS/macOSLauncher
          lipo -create build/macosx/arm64/release/stfc-community-patch-loader build/macosx/x86_64/release/stfc-community-patch-loader -output build/macosx/arm64/release/macOSLauncher.app/Contents/stfc-community-patch-loader
          lipo -create build/macosx/arm64/release/libstfc-community-patch.dylib build/macosx/x86_64/release/libstfc-community-patch.dylib -output build/macosx/arm64/release/macOSLauncher.app/Contents/libstfc-community-patch.dylib
          cp assets/launcher.icns build/macosx/arm64/release/macOSLauncher.app/Contents/Resources
          mv build/macosx/arm64/release/macOSLauncher.app build/macosx/arm64/release/STFC\ Community\ Patch.app

      - name: Sign Universal App Bundle
        continue-on-error: true
        run: codesign --force --verify --verbose --deep --sign "-" build/macosx/arm64/release/STFC\ Community\ Patch.app

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install brew things
        run: brew install create-dmg

      - name: Create installer
        run: create-dmg --filesystem APFS --format ULFO --volname "STFC Community Patch Installer" --volicon assets/launcher.icns --background assets/mac_installer_background.png --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "STFC Community Patch.app" 200 190 --app-drop-link 600 185 stfc-community-patch-installer.dmg build/macosx/arm64/release/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stfc-community-patch-installer
          path: stfc-community-patch-installer.dmg
